// <auto-generated />
using System;
using AdLerBackend.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdLerBackend.Infrastructure.Migrations
{
    [DbContext(typeof(ProductionContext))]
    [Migration("20241220145425_AutoIncrementIds")]
    partial class AutoIncrementIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AdLerBackend.Domain.Entities.H5PLocationEntity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("ElementId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("WorldEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorldEntityId");

                    b.ToTable("H5PLocationEntity");
                });

            modelBuilder.Entity("AdLerBackend.Domain.Entities.WorldEntity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("AtfJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("LmsWorldId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("AdLerBackend.Domain.Entities.H5PLocationEntity", b =>
                {
                    b.HasOne("AdLerBackend.Domain.Entities.WorldEntity", null)
                        .WithMany("H5PFilesInCourse")
                        .HasForeignKey("WorldEntityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AdLerBackend.Domain.Entities.WorldEntity", b =>
                {
                    b.Navigation("H5PFilesInCourse");
                });
#pragma warning restore 612, 618
        }
    }
}
