name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Dotnet for use with actions
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
      - name: Run Tests
        run: |
          dotnet build
          dotnet test AdLerBackend.API/AdLerBackend.API.csproj /p:CollectCoverage=true /p:CoverletOutput=./AdLerBackend.API/code-coverage/ /p:CoverletOutputFormat=lcov
          dotnet test AdLerBackend.Application/AdLerBackend.Application.csproj /p:CollectCoverage=true /p:CoverletOutput=./AdLerBackend.Application/code-coverage/ /p:CoverletOutputFormat=lcov
          dotnet test AdLerBackend.Domain/AdLerBackend.Domain.csproj /p:CollectCoverage=true /p:CoverletOutput=./AdLerBackend.Domain/code-coverage/ /p:CoverletOutputFormat=lcov
          dotnet test AdLerBackend.Infrastructure/AdLerBackend.Infrastructure.csproj /p:CollectCoverage=true /p:CoverletOutput=./AdLerBackend.Infrastructure/code-coverage/ /p:CoverletOutputFormat=lcov

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}