name: Update Swagger Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  update-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Restore and build
        run: |
          dotnet restore AdLerBackend.sln
          dotnet build AdLerBackend.sln --configuration Release --no-restore

      - name: Generate Swagger JSON
        run: |
          mkdir -p Spec
          dotnet swagger tofile --output Spec/swagger.json AdLerBackend.API/bin/Release/net8.0/AdLerBackend.API.dll v1

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update swagger documentation [skip ci]"
          file_pattern: "Spec/*.json"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          skip_dirty_check: false
